version: "3"
services:
  db:
    image: postgres:12
    container_name: "db"
    env_file:
      - .env
    environment:
      POSTGRES_USER: $RDS_USERNAME
      POSTGRES_PASSWORD: $RDS_PASSWORD
      POSTGRES_DB: $RDS_DB_NAME
    ports:
      - "${RDS_PORT}:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d
volumes:
  database:
    driver: local
